baseurl = "https://knowledgebase.satrdays.org/"
languageCode = "en-gb"
title = "SatRdays Knowledge Base"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "Steph Locke"
	description = "The satRdays knowledge base for running and building satRdays"
	copyright = "Released under the CC BY 4.0 license"
	coresite = "//satrdays.org"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/satrdays/knowledgebase"

	version = ""
	logo = "img/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = ["css/satrdays.css"]
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "blue"
    	accent  = "light-blue"

    [params.font]
    	text = "Roboto"
    	code = "Roboto Mono"


[social]
	twitter = "satrdays_org"
	github  = "satrdays"
	email   = ""
	slack   = "https://join.slack.com/t/rusergroups/shared_invite/enQtMjEyNDA3MzcyMjczLTE3NWEzNjQ3MjZiMWM0OGE2ZWFiZDliNTY4NTJjYWY1NGNjMmNlNDUzNzkzOTZmMDBjYjRiZjFhNjk4MDY0ZGY"


[[menu.main]]
	name   = "SatRdays"
	url    = "/"
	weight = 1

[[menu.main]]
	name   = "History"
	url    = "history/"
	weight = 5



[[menu.main]]
	name   = "Roadmap"
	url    = "roadmap/"
	weight = 20


[[menu.main]]
	name   = "Start an event"
	url    = "newevents/"
	weight = 25


[[menu.main]]
	name   = "Diversity"
	url    = "diversity/"
	weight = 35

[[menu.main]]
	name   = "Organising"
	url    = "organising/"
	weight = 30
	
[[menu.main]]
	name   = "Onboarding process"
	url    = "onboarding/"
	weight = 29
	
[[menu.main]]
	name   = "Technology"
	url    = "infrastructure/"
	weight = 40
	
[[menu.main]]
	name   = "Branding"
	url    = "branding/"
	weight = 50

[[menu.main]]
	name   = "Licenses"
	url    = "license/"
	weight = 60

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
